<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Desmond Mariita">
<meta name="dcterms.date" content="2026-07-19">
<meta name="description" content="A credit model approved applicants it had rejected — after they asked for more money. Four applicants that no smaller or shorter loan could rescue flip to approved by borrowing more.">

<title>When recourse runs backwards: an AI-assurance case study in credit scoring – Desmond Mariita</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-a1e0e591d9e784db91f005ccc1a3bac8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="When recourse runs backwards: an AI-assurance case study in credit scoring – Desmond Mariita">
<meta property="og:description" content="A credit model approved applicants it had rejected — after they asked for more money. Four applicants that no smaller or shorter loan could rescue flip to approved by borrowing more.">
<meta property="og:image" content="https://desmond-mariita.github.io/writing/borrow-more/figures/risk-vs-amount.png">
<meta property="og:site_name" content="Desmond Mariita">
<meta property="og:image:height" content="704">
<meta property="og:image:width" content="1216">
<meta name="twitter:title" content="When recourse runs backwards: an AI-assurance case study in credit scoring – Desmond Mariita">
<meta name="twitter:description" content="A credit model approved applicants it had rejected — after they asked for more money. Four applicants that no smaller or shorter loan could rescue flip to approved by borrowing more.">
<meta name="twitter:image" content="https://desmond-mariita.github.io/writing/borrow-more/figures/risk-vs-amount.png">
<meta name="twitter:image-height" content="704">
<meta name="twitter:image-width" content="1216">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Desmond Mariita</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../writing/index.html"> 
<span class="menu-text">Writing</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Desmond-Mariita"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/desmond-mariita"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#the-setup" id="toc-the-setup" class="nav-link active" data-scroll-target="#the-setup">The setup</a></li>
  <li><a href="#recourse-and-where-it-ran-backwards" id="toc-recourse-and-where-it-ran-backwards" class="nav-link" data-scroll-target="#recourse-and-where-it-ran-backwards">Recourse, and where it ran backwards</a></li>
  <li><a href="#the-rest-of-the-audit-briefly" id="toc-the-rest-of-the-audit-briefly" class="nav-link" data-scroll-target="#the-rest-of-the-audit-briefly">The rest of the audit, briefly</a></li>
  <li><a href="#why-you-can-believe-any-of-this" id="toc-why-you-can-believe-any-of-this" class="nav-link" data-scroll-target="#why-you-can-believe-any-of-this">Why you can believe any of this</a></li>
  <li><a href="#what-it-does-not-claim" id="toc-what-it-does-not-claim" class="nav-link" data-scroll-target="#what-it-does-not-claim">What it does not claim</a></li>
  <li><a href="#one-more-thread" id="toc-one-more-thread" class="nav-link" data-scroll-target="#one-more-thread">One more thread</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">When recourse runs backwards: an AI-assurance case study in credit scoring</h1>
  <div class="quarto-categories">
    <div class="quarto-category">AI assurance</div>
    <div class="quarto-category">EU AI Act</div>
    <div class="quarto-category">model risk</div>
    <div class="quarto-category">recourse</div>
  </div>
  </div>

<div>
  <div class="description">
    A credit model approved applicants it had rejected — after they asked for more money. Four applicants that no smaller or shorter loan could rescue flip to approved by borrowing more.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Desmond Mariita </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 19, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>I audited a credit-scoring model against the EU AI Act. The result I keep coming back to has nothing to do with accuracy or fairness. It is this: a handful of the applicants the model rejected could only have been approved by asking for <em>more</em> money. That is a flaw in the model, not advice anyone could act on.</p>
<p>One applicant makes the point on their own. They asked for a loan of 409 Deutsche Mark (the data is early-1990s German bank records) and were rejected. Hold everything else about them fixed, slide the requested amount up and down, and watch what the model does:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/risk-vs-amount.png" class="img-fluid figure-img"></p>
<figcaption>Predicted risk for one rejected applicant, sweeping only the loan amount. The model approves them (green bands) in two narrow windows, roughly 980–1,200 and 1,290–1,480 DM, and rejects them everywhere else, including the 409 they requested.</figcaption>
</figure>
</div>
<p>There is no coherent advice you could give this person. Smaller loans are rejected, so “borrow less” is out. Most larger loans are rejected too. The only route to a yes is to land inside one of two arbitrary green slivers, and nothing about the applicant explains where those slivers fall. No loan officer would ever say it. The model would, for four of the people it turned down.</p>
<blockquote class="blockquote">
<p><strong>The finding, in four lines</strong> - <strong>What:</strong> 4 of the 19 applicants that no smaller or shorter loan could rescue flip to approved by asking for a bigger one. - <strong>Why it matters:</strong> the obvious advice to give them, “reduce your loan,” is exactly backwards. - <strong>How I caught it:</strong> an exhaustive grid over every smaller or shorter loan, then a probe the opposite way on the cases no reduction could fix. - <strong>Deployer action:</strong> investigate as model risk; keep it out of customer-facing advice.</p>
</blockquote>
<section id="the-setup" class="level2">
<h2 class="anchored" data-anchor-id="the-setup">The setup</h2>
<p>The model is a LightGBM classifier trained on the German Credit dataset, with a test AUROC of 0.769. LightGBM is a gradient-boosted tree ensemble, widely used for tabular credit data. Any single tree would be readable; the full ensemble is a black box, which makes its explanations and its recourse worth auditing. I scored it at a cost-sensitive 5:1 threshold, the setting that treats approving a bad loan as five times worse than turning away a good one. This is the high-risk credit scoring that Annex III of the EU AI Act now covers.</p>
<p>I built it and I audited it. That makes this a self-assessment, not an independent audit, and I will come back to why the difference is load-bearing. Everything is public and pre-registered: https://github.com/Desmond-Mariita/eu-ai-act-credit-assurance.</p>
</section>
<section id="recourse-and-where-it-ran-backwards" class="level2">
<h2 class="anchored" data-anchor-id="recourse-and-where-it-ran-backwards">Recourse, and where it ran backwards</h2>
<p>Recourse asks what a rejected applicant would have to change to get an approval. For a loan model the actionable answers are a shorter term or a smaller amount, so I searched every valid combination of loan duration and credit amount below what each applicant asked for, and scored each one against the frozen, hash-pinned model.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Of the 151 rejected applicants…</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>reach approval with a smaller or shorter loan</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">87.4%</td>
</tr>
<tr class="even">
<td>cannot: no smaller or shorter loan works</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">12.6%</td>
</tr>
<tr class="odd">
<td>&nbsp;&nbsp;→ but approved if they ask for a <em>bigger</em> loan</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>&nbsp;&nbsp;→ genuinely stuck: no single change works</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p>So 87.4% of the rejected applicants have a way back to approval through a smaller or shorter loan, more often a shorter term than a smaller amount. When a bank declines a loan it owes the applicant a reason for the decision, and banks call these “reason codes.” Across the declined applicants the most-cited reason is <strong>loan duration</strong> (100 times), with <strong>credit amount</strong> next (59). That is the kind of explanation a deployer can defensibly hand a customer.</p>
<p>Then there is the other 12.6%, the 19 people no reduction can help. Here is a mistake worth putting on the record. My first write-up said those 19 rejections “rest on non-actionable factors” like credit history or account status, the things an applicant cannot change on a form. It sounded reasonable. It was also an overclaim: all I had shown was that no <em>reduction</em> worked. I had said nothing about <em>why</em>.</p>
<p>Searching the other direction broke that story. Four of the 19 were not blocked by an immutable trait, by something fixed like credit history that an applicant cannot change. They flip to approved by requesting a larger loan:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Requested (DM)</th>
<th style="text-align: right;">Approved once they ask for</th>
<th style="text-align: right;">Model’s original risk</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">409</td>
<td style="text-align: right;">980</td>
<td style="text-align: right;">0.55</td>
</tr>
<tr class="even">
<td style="text-align: right;">652</td>
<td style="text-align: right;">3,516</td>
<td style="text-align: right;">0.73</td>
</tr>
<tr class="odd">
<td style="text-align: right;">741</td>
<td style="text-align: right;">3,516</td>
<td style="text-align: right;">0.77</td>
</tr>
<tr class="even">
<td style="text-align: right;">959</td>
<td style="text-align: right;">3,516</td>
<td style="text-align: right;">0.63</td>
</tr>
</tbody>
</table>
<p>A monotone model would push predicted risk in one steady direction as the loan grows. This one does not: for these four applicants, more credit means lower predicted risk. And it is specifically the size of the loan: a longer repayment term flipped none of them, only a larger sum. Stranger still, three of them cross into approval at exactly 3,516 DM. That is a fingerprint of the model’s geometry; nothing obvious about the three applicants explains it. A boosted tree ensemble predicts in steps, changing its mind only at the split points it learned from the data, so different applicants get funnelled to the same handful of amounts. I had been one edit away from publishing a causal claim the data did not support.</p>
<blockquote class="blockquote">
<p><strong>If you deploy a model like this:</strong> the four increase-flip cases are model risk, not recourse, so flag them for review. And search in <em>both</em> directions before you trust a “no recourse” result, because a one-way search quietly relabels non-monotonicity as immutability.</p>
</blockquote>
<p>I did not get here with an off-the-shelf tool. My first attempt used a popular counterfactual library, which proposed loans of 13.1 months and other fractions no bank offers. I threw it out and built the integer grid instead. That library is not the villain. A search that fails to find a counterfactual and a case where none exists look identical from the outside, and for an audit that gap is the whole job.</p>
</section>
<section id="the-rest-of-the-audit-briefly" class="level2">
<h2 class="anchored" data-anchor-id="the-rest-of-the-audit-briefly">The rest of the audit, briefly</h2>
<p>The borrow-more result is the one that surprised me most, but it is not the whole audit.</p>
<p>On fairness, the disparities run the wrong way: women and younger applicants are declined more often. None of it clears significance on a 300-row test set (sex false-positive-rate difference, permutation test p = 0.091). I will not call that “no bias.” The model trains directly on a sex proxy, age, and foreign-worker status, and 300 rows is too few to rule out a real gap. These are monitoring flags, not a clean bill of health.</p>
<p>On robustness, 13.3% of applicants sit within a hair of the decision threshold, where small synthetic input noise flips their result. The core faithfulness result also replicated on a second, structurally different dataset, Give Me Some Credit; recourse I tested only on German Credit.</p>
</section>
<section id="why-you-can-believe-any-of-this" class="level2">
<h2 class="anchored" data-anchor-id="why-you-can-believe-any-of-this">Why you can believe any of this</h2>
<p>Any of this only counts if you can trust that the audit produced it honestly, and self-assessment is where that trust runs thinnest. The recourse result comes from an exhaustive, direction-constrained search over a frozen, hash-verified model. Because the search checks every candidate rather than sampling, there is no stochastic solver whose randomness I could have quietly steered toward a nicer number. And I committed the hypotheses and the method to a signed, timestamped record before running anything, anchored to a public blockchain block, so I could not have moved the goalposts after seeing the results.</p>
<p>I also got things wrong on the record. The “non-actionable factors” overclaim above is one of them. I put the whole audit through a panel of separate AI models, each prompted to attack it; they caught a real bug (an explanation method quietly sampling impossible applicants) and several softer overstatements, which I fixed across versions. I re-cut a release tag once, early on, before I learned that you do not move a published tag. Since then I supersede rather than move. That review is quality control, not independent human assurance, and I say so in every document. Confusing the two would undercut the whole point of the project.</p>
</section>
<section id="what-it-does-not-claim" class="level2">
<h2 class="anchored" data-anchor-id="what-it-does-not-claim">What it does not claim</h2>
<p>This is not a statement that the model is EU AI Act compliant. It is a self-assessment of four testable properties. The obligations that need a real deployment are listed as open gaps: a quality management system, production logging, post-market monitoring, and a real Data Protection Impact Assessment (the privacy review GDPR requires before high-risk processing). The missing piece is an independent human reviewer, someone who built neither the model nor the audit. That is the distance between “I checked my own work carefully” and “someone qualified checked it,” and I am not going to paper over it.</p>
<p>Consider this an open invitation. If you have the background to judge this work (machine learning, statistics, the EU AI Act, or GDPR) and you had no hand in building it, I would like you to review it. The repo ships a structured reviewer template for exactly this, and I will publish your signed verdict in full, including anything it gets wrong. An audit that no independent expert has checked still needs that review before anyone treats it as independent assurance.</p>
</section>
<section id="one-more-thread" class="level2">
<h2 class="anchored" data-anchor-id="one-more-thread">One more thread</h2>
<p>When I stopped asking whether the model’s <em>decisions</em> were sound and started asking whether its <em>explanations</em> were faithful, whether SHAP and LIME actually described what the model was doing, the honest answer turned out to be “it depends on how you measure.” One of the most popular explanation tools was the source of those impossible applicants. If you want the technical teardown, I wrote it up separately: <a href="../../writing/faithfulness/index.html">Part 2</a>.</p>
<p>The repo, the signed audit opinion, and the full evidence trail are here: https://github.com/Desmond-Mariita/eu-ai-act-credit-assurance. I am moving into AI assurance and governance work. If this is the kind of work your team needs done, with this level of traceability, I would like to hear from you.</p>
<p><em>Prefer a typeset copy? <a href="article-part1-borrow-more.pdf">Download the PDF</a>.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/desmond-mariita\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Desmond Mariita</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a>. Source and evidence: <a href="https://github.com/Desmond-Mariita/eu-ai-act-credit-assurance">eu-ai-act-credit-assurance</a>.</p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>